Resources:
    MyInstanceProfileRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - ec2.amazonaws.com
                      Action: 'sts:AssumeRole'
                Path: /
                Policies:
                    - PocilyName: MYInstanceProfilePolicy
                      PolicyDocument:
                        Version: 2012-10-17
                        Statment:
                            - Effect: Allow
                              Action:
                                - 's3:Get*'
                                - 's3:List*'
                              Resource: '*'      