AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Nested Stack

Parameters:
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR range
  Subnet1Public:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for subnet1
  Subnet2Public:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for Subnet2Public
  Subnet3Public:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR block for Subnet3Public
  Subnet1Private:
    Type: String
    Default: 10.0.4.0/24
    Description: CIDR block for Subnet1Private
    Subnet2Private:
    Type: String
    Default: 10.0.5.0/24
    Description: CIDR block for Subnet2Private
  Subnet3Private:
    Type: String
    Default: 10.0.6.0/24
    Description: CIDR block for Subnet3Private

  


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
        default: 
        Parameters:
          - VpcBlock
          - Subnet1Public
          - Subnet2Public
          - Subnet3Public
          - Subnet1Private
          - Subnet2Private
          - Subnet3Private
    ParameterLabels:
      VpcBlock:
        default: VPC CIDR range selection


Resources:
  TemplateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"

  Subnet1:
    Type: AWS::EC2:Subnet
    Properties:
      VpcId: !Ref TemplateVPC
      CidrBlock: !Ref Subnet1Public
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet1-public"
      AvailabilityZone: us-east-1a
  Subnet2:
    Type: AWS::EC2:Subnet
    Properties:
      VpcId: !Ref TemplateVPC
      CidrBlock: !Ref Subnet2Public
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet2-public"
      AvailabilityZone: us-east-1b

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TemplateVPC
      Tags:
        - Key: Name
          Value: Public Subnet
        - Key: Network
          Value: Public
  
  RouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref RouteTable

  InternetGW:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAtt:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGW
      VpcId: !Ref TemplateVPC
  
  VPCRoute:
    DependsOn: VPCGatewayAtt 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGW


Outputs:
  Subnet1Id:
    Description: Subnet 1 Id
    Value: !Ref Subnet1

  VPCId:
    Description: VPC Id
    Value: !Ref TemplateVPC

    #M5.large 
    #30GB