AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keypair
  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: QA
    AllowedValues: 
      - QA
      - prod


Mappings:
  MyRegionMap:
    us-east-1:
      AMIID: ami-0a887e401f7654935
    sa-east-1:
      AMIID: ami-080a223be3de0c3b8     
  MyEnvironmentMap:
    QA:
      instanceType: t2.micro
    prod:
      instanceType: t2.small      

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - AMIID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKey
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: SG from SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance 
